skip Download feature flags step

diff --git a/.github/workflows/build_pypi.yml b/.github/workflows/build_pypi.yml
--- a/.github/workflows/build_pypi.yml
+++ b/.github/workflows/build_pypi.yml
@@ -110,25 +110,25 @@ jobs:
       - name: Collect static
         run: poetry run python label_studio/manage.py collectstatic
 
-      - name: Download feature flags
-        env:
-          LAUNCHDARKLY_COMMUNITY_SDK_KEY: ${{ secrets.LAUNCHDARKLY_COMMUNITY_SDK_KEY }}
-          LAUNCHDARKLY_DOWNLOAD_PATH: "label_studio/feature_flags.json"
-        run: |
-          set -xeuo pipefail
-          curl \
-            --connect-timeout 30 \
-            --retry 5 \
-            --retry-delay 10 \
-            -H "Authorization: $LAUNCHDARKLY_COMMUNITY_SDK_KEY" \
-            "https://sdk.launchdarkly.com/sdk/latest-all" >"$LAUNCHDARKLY_DOWNLOAD_PATH"
-          if [ "$(jq 'has("flags")' <<< cat $LAUNCHDARKLY_DOWNLOAD_PATH)" = "true" ]; then
-            echo "feature_flags.json is valid"
-          else
-            echo "feature_flags.json is invalid"
-            cat $LAUNCHDARKLY_DOWNLOAD_PATH
-            exit 1
-          fi
+#      - name: Download feature flags
+#        env:
+#          LAUNCHDARKLY_COMMUNITY_SDK_KEY: ${{ secrets.LAUNCHDARKLY_COMMUNITY_SDK_KEY }}
+#          LAUNCHDARKLY_DOWNLOAD_PATH: "label_studio/feature_flags.json"
+#        run: |
+#          set -xeuo pipefail
+#          curl \
+#            --connect-timeout 30 \
+#            --retry 5 \
+#            --retry-delay 10 \
+#            -H "Authorization: $LAUNCHDARKLY_COMMUNITY_SDK_KEY" \
+#            "https://sdk.launchdarkly.com/sdk/latest-all" >"$LAUNCHDARKLY_DOWNLOAD_PATH"
+#          if [ "$(jq 'has("flags")' <<< cat $LAUNCHDARKLY_DOWNLOAD_PATH)" = "true" ]; then
+#            echo "feature_flags.json is valid"
+#          else
+#            echo "feature_flags.json is invalid"
+#            cat $LAUNCHDARKLY_DOWNLOAD_PATH
+#            exit 1
+#          fi
 
       - name: Package
         env:
